// <auto-generated />
using System;
using Footballito.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Footballito.Persistence.Migrations
{
    [DbContext(typeof(FootballContext))]
    [Migration("20251230032719_SeedTeams")]
    partial class SeedTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Footballito.Persistence.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayTeamId = 2,
                            AwayTeamScore = 1,
                            Date = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 1,
                            HomeTeamScore = 2
                        },
                        new
                        {
                            Id = 2,
                            AwayTeamId = 4,
                            AwayTeamScore = 3,
                            Date = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 3,
                            HomeTeamScore = 1
                        },
                        new
                        {
                            Id = 3,
                            AwayTeamId = 6,
                            AwayTeamScore = 0,
                            Date = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 5,
                            HomeTeamScore = 0
                        });
                });

            modelBuilder.Entity("Footballito.Persistence.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Lionel",
                            LastName = "Messi",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Sergio",
                            LastName = "Busquets",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Cristiano",
                            LastName = "Ronaldo",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Karim",
                            LastName = "Benzema",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Marcus",
                            LastName = "Rashford",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Mohamed",
                            LastName = "Salah",
                            TeamId = 4
                        });
                });

            modelBuilder.Entity("Footballito.Persistence.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Barcelona",
                            Name = "FC Barcelona"
                        },
                        new
                        {
                            Id = 2,
                            City = "Madrid",
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 3,
                            City = "Manchester",
                            Name = "Manchester United"
                        },
                        new
                        {
                            Id = 4,
                            City = "Liverpool",
                            Name = "Liverpool FC"
                        },
                        new
                        {
                            Id = 5,
                            City = "Munich",
                            Name = "Bayern Munich"
                        },
                        new
                        {
                            Id = 6,
                            City = "Turin",
                            Name = "Juventus"
                        },
                        new
                        {
                            Id = 7,
                            City = "Paris",
                            Name = "Paris Saint-Germain"
                        },
                        new
                        {
                            Id = 8,
                            City = "London",
                            Name = "Chelsea FC"
                        },
                        new
                        {
                            Id = 9,
                            City = "Milan",
                            Name = "AC Milan"
                        },
                        new
                        {
                            Id = 10,
                            City = "Buenos Aires",
                            Name = "River Plate"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
